[package]
name = "archon"
version = "0.1"
authors = [
    "jiami <jiami@creditease.cn>",
]
build_opts = []
deps = []

[distribution]
build_opts = []
pack_extras = ["templates"]
cross_targets = [["linux", "amd64"]]

[assets]
url_prefix = "/assets"
assets_mapping_pkg = "main"
image_exts = [".png", ".jpg", ".jpeg", ".gif"]
deps = [
    "es5-shim@4.5.9",
    "react@0.14.1",
    "react-dom@0.14.1",
    "react-router@v1.0.0-rc1",
    "history@1.13.1",
    "lodash@3.6.0",
    "radium@0.15.3",
    "color@0.10.1",
    "classnames@2.2.5",
    "redux@3.6.0",
    "react-redux@4.0.0",
    "redux-logger@2.7.4",
    "whatwg-fetch@2.0.1",
    "cookie@0.3.1",
    "moment@2.17.1",
    "xterm@2.1.0",
    "utf-8-validate@1.2.1",
    "bufferutil@1.3.0",
    "websocket@1.0.23",
    "jquery@3.1.1",
    "js-base64@2.1.9",

    "uglifyify@3.0.4",
    "browserify@13.3.0",
    "envify@4.0.0",
    "babelify@7.3.0",
    "babel-preset-es2015@6.18.0",
    "babel-preset-react@6.16.0",
    "nib@1.1.2",
    "stylus@0.54.5",
    "coffeeify@2.1.0",
]

[[assets.entry]]
name = "archon"
